### ISSUE TITLE
the game amount of promote matches of this round and some last round is only 20+

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#108]
it was 50+
this round
17 : 0 : 12 (58.62%) 29 / 20 promotion 
last round
15 : 1 : 15 (50.00%) 31 / 20 promotion 
30 : 4 : 30 (50.00%) 64 / 50 promotion

**Comment by Vandertic** [comment]
My fault. I set it to 20 for some test networks and forgot to update. Now corrected.
