### ISSUE TITLE
Is g130 network files broken?

### ISSUE THREAD

**Issue by nanzi** [CuriosAI/sai#110]
[b06e8f6a](http://sai.unich.it/network-profiles/b06e8f6a8e8568fd8a26048781d5eb8acbda4f8af93dfb084ef71ef73fea9628) was arranged match games then autogtp.exe would crash.
And I noticed now (5:55 utc +0) most clients is offline.

**Comment by Vandertic** [comment]
Thanks. We had a problem which we are now trying to solve. The broken network was deleted and self-play are back.

**Comment by nanzi** [comment]
`Uploading match: e79f1ee7681f4a72a2e5cfc3182bbb99.sgf for networks 00a80c6d0a09c3fa224fd2cc1db81bebb0e46c52332d91b7b44ebd4f3915d480 and 6eb7a4bedec3ff89ddb64f17819ffed9732243df11d7841c1804431c77d95bd5
Upload failed. Curl Exit code: 22`

Both 00a80c6 and 6eb7a4 are generation-130, there is a sequence mistake in server match arrangement.



Start Date | Network Hashes | Wins : Draws : Losses | Games | Type
-- | -- | -- | -- | --
2020-03-26 17:31 | 00a80c6d  VS  07ad6a9b | 33 : 2 : 26 (55.74%) | 61 / 50 | promotion

**Comment by nanzi** [comment]
There is a panel matches set for current SAI303 with its g-130 cousins as far as I know.

**Comment by Vandertic** [comment]
Corrected now. The main machine on which the pipeline and training were done dead yesterday and we had to move everything quickly to another pc. We expect small problems for some time. Please report any problem.

And possibly delete the .bin and .gz files from your run directory to stop the upload attempts.
