### ISSUE TITLE
try training with python parse.py 16 128 /tmp/test.txt.0 found error

### ISSUE THREAD

**Issue by tang3** [CuriosAI/sai#113]
try training with python parse.py 16 128 /tmp/test.txt.0 found 

 File "/data/sai-sai-0.17/training/tf/chunkparser.py", line 210, in convert_v1_to_v2
    stm = float(tomove_and_global_info[0])
ValueError: could not convert string to float: '00000001c000060b80000000000000000000000000020100010000020000640000980050a004900092803000000'

how can i sovle it

**Comment by Vandertic** [comment]
Can you attach test.txt.0 file?

**Comment by Vandertic** [comment]
The format of the chunks file should be something like:

`0000000000008012000000000000000000000000000000008000002040000000000000008004080800000000000`
`0000000000000000008000000000000000000020000000000000000000000010010000010010300180000000000`
`0000000000008012008000000000000000000020000000008000002040000010010000018014380980000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000008004080000000000000`
`0000000000008012008000000000000000000020000000008000002040000010010000008014080800000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000010000300180000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
`0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
`0 7.5 2a2306cac746cb600f94fb7593d591ed460a022f9a47dd6ec5af5912eeb9fb38 20`
`1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 10 1 1 1 1 1 1 1 1 1 1 1 2 9 2 1 4 1 1 1 1 1 13 1 1 1 36 1 0 1 2 41 2 7 60 2 1 1 1 0 1 1 0 1 1 2 1 1 1 4 8 2 0 29 2 1 1 1 1 1 1 1 11 2 1 2 1 3 1 2 2 4 2 4 1 1 2 33 8 2 2 4 2 2 2 2 2 2 2 4 28 503 4 2 1 1 212 14 5 6 6 5 5 4 6 5 6 3 5 13 14 1 4 1 5 2 10 6 6 204 7 6 5 3 4 3 5 5 6 12 1 1 1 1 0 14 9 49 7 47 5 3 2 2 4 2 2 5 6 2 1 4 1 2 12 79 13 6 2 2 1 1 1 2 69 1 2 2 1 1 1 1 0 1 198 29 4 2 1 1 1 1 4 2 1 1 1 1 1 1 1 1 2 10 12 8 1 1 0 1 1 3 2 2 1 0 1 1 1 1 8 6 5 6 4 3 1 1 1 2 2 6 3 1 5 1 1 1 3 21 4 0 4 5 2 9 1 1 2 3 3 9 89 0 26 1 1 1 1 350 1 11 6 4 8 2 1 1 6 32 2 9 3 4 1 1 1 0 0 15 24 9 38 38 38 8 1 1 1 0 1 0 2 1 1 1 0 0 0 1 11 33 116 148 53 1 0 1 1 0 0 4 1 1 5 1 1 4 9 1 1 1 1 2 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1`
`-1 -3.30518 0.113235 0.406399`

**Comment by tang3** [comment]
> Can you attach test.txt.0 file?

i use "dump_supervised bigsgf.sgf train.out" to generate the train data,like:

00000220001e781470c3f608443d520058720715a24142e0c06f241924ba9865670346a6400828ed0c22c140000
00000220001e781470c3f608443d520058720715a24142e0c06f241924ba9865670346a6400828ed0c22c140000
00000220001e781470c3f608443d520058720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
00000220001e781470c3f608443d520058720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
00000220001e781470c3f608443d520050720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
02000220001e781470c3f608443d520050720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
02000220001c781470c3f608443d520050720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
02000220001c781470c3f608443d520050720715a24142e0c06f241924b89865670346a6400828ed0c22c140000
058005d3c0e1872800240806bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
058005d3c0e1872800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
058005d3c0e1872800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
058005d3c0e1862800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
058005d3c0e1862800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
018005d3c0e1862800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
018005d3c0e1862800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
01800593c0e1862800240804bbc08d9f830c18000d8e8101319003e20044648898988110bff4921293813000000
0 7.5  0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
-1 0 0 0

**Comment by tang3** [comment]
> The format of the chunks file should be something like:
> 
> `0000000000008012000000000000000000000000000000008000002040000000000000008004080800000000000`
> `0000000000000000008000000000000000000020000000000000000000000010010000010010300180000000000`
> `0000000000008012008000000000000000000020000000008000002040000010010000018014380980000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000008004080000000000000`
> `0000000000008012008000000000000000000020000000008000002040000010010000008014080800000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000010000300180000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
> `0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`
> `0 7.5 2a2306cac746cb600f94fb7593d591ed460a022f9a47dd6ec5af5912eeb9fb38 20`
> `1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 10 1 1 1 1 1 1 1 1 1 1 1 2 9 2 1 4 1 1 1 1 1 13 1 1 1 36 1 0 1 2 41 2 7 60 2 1 1 1 0 1 1 0 1 1 2 1 1 1 4 8 2 0 29 2 1 1 1 1 1 1 1 11 2 1 2 1 3 1 2 2 4 2 4 1 1 2 33 8 2 2 4 2 2 2 2 2 2 2 4 28 503 4 2 1 1 212 14 5 6 6 5 5 4 6 5 6 3 5 13 14 1 4 1 5 2 10 6 6 204 7 6 5 3 4 3 5 5 6 12 1 1 1 1 0 14 9 49 7 47 5 3 2 2 4 2 2 5 6 2 1 4 1 2 12 79 13 6 2 2 1 1 1 2 69 1 2 2 1 1 1 1 0 1 198 29 4 2 1 1 1 1 4 2 1 1 1 1 1 1 1 1 2 10 12 8 1 1 0 1 1 3 2 2 1 0 1 1 1 1 8 6 5 6 4 3 1 1 1 2 2 6 3 1 5 1 1 1 3 21 4 0 4 5 2 9 1 1 2 3 3 9 89 0 26 1 1 1 1 350 1 11 6 4 8 2 1 1 6 32 2 9 3 4 1 1 1 0 0 15 24 9 38 38 38 8 1 1 1 0 1 0 2 1 1 1 0 0 0 1 11 33 116 148 53 1 0 1 1 0 0 4 1 1 5 1 1 4 9 1 1 1 1 2 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1`
> `-1 -3.30518 0.113235 0.406399`

how can i generate like this

**Comment by Vandertic** [comment]
You need to generate self-plays adding the command-line options `--adv_features --chainlibs_feat --chainsize_feat` to the `sai` command.

**Comment by Vandertic** [comment]
I wrote an explanation on Discord
![image](https://user-images.githubusercontent.com/27057329/79732182-9ebbe800-82f3-11ea-9e08-80c2334b5ac1.png)

**Comment by tang3** [comment]
> You need to generate self-plays adding the command-line options `--adv_features --chainlibs_feat --chainsize_feat` to the `sai` command.

I use this solve my problem, thanks~
