### ISSUE TITLE
recommendations on text on the invite page

### ISSUE THREAD

**Issue by RosaMGini** [CuriosAI/sai#12]
after a second feedback i suggest we modify "Download the latest release of SAI" -> "Open this this page and download the latest release of SAI fitting the characteristics of your computer"

let's include here other recommendations on the invite page

**Comment by amato-gianluca** [comment]
With the link in "this page" ?

**Comment by RosaMGini** [comment]
also: at the end, after "You will also be able to play with SAI 19x19, however on this board SAI will be quite weak for many month", add "In order to play, if you are a Windows user, please double click on sai9x9.bat in the same archive."

**Comment by RosaMGini** [comment]
@MistyDay86 : I think you should try to play with 9x9 SA and then write instructions for the other players
