### ISSUE TITLE
[Question] License of trained weights

### ISSUE THREAD

**Issue by y-ich** [CuriosAI/sai#126]
Hi, thank you for your great project!

I want to use SAI's weights in my commercial app.
Is the license same as Leela Zero?
(Leela Zero's weights are public domain. https://github.com/leela-zero/leela-zero/issues/1220#issuecomment-382456362)

Thanks!

**Comment by Vandertic** [comment]
Thank you for asking @y-ich. We are currently asking around and checking legal stuff to be sure that there is no problem with that, but we are all in favor to let you use SAI's weights for your app. 

We hope to have the detailed answer in a few days.

**Comment by y-ich** [comment]
@Vandertic san

Thank you for your efforts, I am looking forward to your answer!

**Comment by amato-gianluca** [comment]
Hi @y-ich, 
we have decided to distribute the weights of the neural networks according to the terms of the CC BY 4.0 licence. Is this fine for your app? We will update the SAI website with the relevant details in the coming days.

**Comment by y-ich** [comment]
@amato-gianluca san,

Thank you for let me know it!
So I think that I can use SAI's weight with your copyright notice. It that right?
Currently I prepare a statement "Powered by neural networks of SAI (https://github.com/sai-dev/sai)" at reference description in my app.
I guess that you will disclose your copyright notice as "the relevant details".
I am looking forward to it.

Thank you for your efforts!

**Comment by amato-gianluca** [comment]
> So I think that I can use SAI's weight with your copyright notice. It that right?
> Currently I prepare a statement "Powered by neural networks of SAI (https://github.com/sai-dev/sai)" at reference description in my app.

That's perfect. Just replace https://github.com/sai-dev/sai with http://sai.unich.it/, since sai.unich.it is the website where neural networks are stored and trained.

--gianluca

**Comment by y-ich** [comment]
@amato-gianluca san,

Thank you!
I replace it according to your comment.

I am looking forward to SAI's growth.
