### ISSUE TITLE
will sai use quantize on 20x256 nets?

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#127]
such as
https://github.com/leela-zero/leela-zero/blob/next/training/tf/quantize_weights.py

**Comment by Vandertic** [comment]
I think it can be done in the same way as LZ (more or less). I don't see if there is actually a strong reason to do this though.
Maybe some user could try to quantize the official weights and we can check if there is strength loss?

**Comment by l1t1** [comment]
thanks
