### ISSUE TITLE
self-play games lost comments when I interrupt autogtp with the q command

### ISSUE THREAD

**Issue by nanzi** [CuriosAI/sai#128]
http://sai.unich.it/view/056905cbd8c7a7747d11660a4afd8fe39b54bbe06da21b19b9649d7a278fbb2a?viewer=wgo
This is one new self-play game start from move 1 
which I quit with "q" input on move 2 or 3, saved, then started autogtp and finished.
But with this link, I only see moves information after move 3. 
Will this (the interruption) change the real training file? Or it's a side effect on sgf save procession?

**Comment by Vandertic** [comment]
It a known problem, but it only affects the sgf comments, which are not saved when you interrupt `autogtp` with te `q` command. Sorry about that and thank you for pointing out it anyway.
