### ISSUE TITLE
katago training so fast

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#135]
https://katagotraining.org/networks/

**Comment by l1t1** [comment]
https://katagotraining.org/
>Stats for kata1
The current ongoing run is named kata1 and began on 2020-11-28 20:23:43 UTC.
Data Generation
Across all time, 22 distinct users have uploaded 59146398 rows of training data, 1089138 training games, and 38114 rating games.
In the last week, 20 distinct users have uploaded 46149403 rows of training data, 849328 new training games, and 22767 new rating games.

**Comment by l1t1** [comment]
the 1st day grow very fast, the next 30 days slow down.
![2020-12-31_081710](https://user-images.githubusercontent.com/23301704/103387837-eb251c00-4b40-11eb-89e9-f5fa854c0455.png)

**Comment by cryptsport** [comment]
> the 1st day grow very fast, the next 30 days slow down.
> ![2020-12-31_081710](https://user-images.githubusercontent.com/23301704/103387837-eb251c00-4b40-11eb-89e9-f5fa854c0455.png)

distributed training started from the kata1-b40c256-s5109387264-d1232289301 2020-12-18 08:13:52 UTC network. previous networks - g170 https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html

**Comment by l1t1** [comment]
> > the 1st day grow very fast, the next 30 days slow down.
> > ![2020-12-31_081710](https://user-images.githubusercontent.com/23301704/103387837-eb251c00-4b40-11eb-89e9-f5fa854c0455.png)
> 
> distributed training started from the kata1-b40c256-s5109387264-d1232289301 2020-12-18 08:13:52 UTC network. previous networks - g170 https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html

thanks
