### ISSUE TITLE
So many match games? 

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#14]
The number of self-playing games is twice that of the match games.  But LZ's self-playing game is five times that of the match games.  why?
I guess you also use match games to train, is it right?

**Comment by Vandertic** [comment]
Our learning pipeline is different from LZ's. See the [wiki](https://github.com/sai-dev/sai/wiki/Progress).
The number of games and matches are surely not optimal, and may well change in the future, anyway at the moment we are doing 4000 self-plays per generation, with 10x50 promotion matches, 5x40 reference matches and 16x30/4 panel matches. So it should be 5 self-plays for every match, like LZ.
We could decrease the number of matches in the future. We will see.

**Comment by kennyfs** [comment]
Great answer, thank you.
