### ISSUE TITLE
Doesn't compile CPU only version

### ISSUE THREAD

**Issue by GD-fix** [CuriosAI/sai#144]
OS: OpenSUSE Tumbleweed
Despite of using "#define USE_CPU_ONLY" (in config.h) "cmake --build" gets:
"CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "2.2")
Call Stack (most recent call first):
  cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindOpenCL.cmake:135 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)"
unlike compilable LeelaZero...

How to compile CPU only version or (better) download compiled 64 bit one (as here: https://github.com/lightvector/KataGo/releases)?

**Comment by amato-gianluca** [comment]
Commit 0883204f0bd16af0740fee733e9382f6b5e50c6a contains a fix for the compilation process.

I am closing this issue, but fill free to open a new one with the request for Linux executables. We will think about this.
