### ISSUE TITLE
autogtp build error

### ISSUE THREAD

**Issue by broody** [CuriosAI/sai#147]
Hello,

I'm running into an error when trying to build autogtp. Attached is the log file. Trying this on Ubuntu 20.04.

Thanks

[build.log](https://github.com/sai-dev/sai/files/8989042/build.log)

**Comment by amato-gianluca** [comment]
The latest commits of SAI require Qt version 5.14, while Ubuntu 20.04 has Qt version 5.12. You may either:

1. Compile version 0.18.2, which works with older Qt versions (<code>git checkout sai-0.18.2</code>);
2. Install a newver version of Qt. For example [https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.0-focal](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.0-focal) is a repository with Qt 5.15 for Ubuntu.

--gianluca

**Comment by broody** [comment]
Thanks!
