### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#15]
Will the network size be bigger in the future?
Will this plan last until it become very strong?

**Comment by Vandertic** [comment]
Hi, sorry if it took me some time to answer, but I missed your posts until now.
Thank you for your questions.

We are training (B) 9x192 and (C) 12x256 at the same time as (A) 6x128. Self-plays will be done on the smaller network (A) until we see that larger networks are needed and then there will be the scale up.
As soon as we go to (B) 9x192, I will start training (D) 20x256 that will be our main target. larger networks may be considered in due time.

Anyway, before we scale up on the network, we will progressively increase visits. We started at 400 and we are now at 800.

**Comment by kennyfs** [comment]
Great answer 👍
Thank you.
