### ISSUE TITLE
More participants? 

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#16]
If the goal of this project is to reach superhumanity, obviously it's not enough.  
Does anyone have some ideas to let more people know about this project and help?

**Comment by Vandertic** [comment]
You are completely right of course. We are almost ready to make an announcement on LZ forum.
Then we will advertise on social media and every other possible channel. You are welcome to tell people you know, as soon as we make the announcement.

We are waiting just to have Windows release 0.17.4, updated to the latest commits that correct some unwanted behaviour that would often lead to wrong jigo.

Thank you again for your interest and your support.

**Comment by Vandertic** [comment]
I made the announcement! Tell everybody! :-)
