### ISSUE TITLE
Invalid authentication error

### ISSUE THREAD

**Issue by Phelanpt** [CuriosAI/sai#17]
I tried setting up an account, and am now trying to connect a cpu autogtp instance, but I keep getting "invalid authentication", followed by a JSON parse error "illegal value".
I'm pretty sure I put in my auth details correctly on the hta page, so I'm not sure what might be going wrong. Anyone else having a similar issue?

**Comment by kennyfs** [comment]
No, I don't have that issue.
Can you check if the input is correct?
Or did you not activate your account by opening an email?

Phelanpt <notifications@github.com> 於 2019年10月28日 週一 06:59 寫道：

**Comment by Vandertic** [comment]
Probably wrong authentication. Can you create a new user and try again?  (it's OK to use the same email, but you have to change the computername)

**Comment by egri-nagy** [comment]
I have the same issue. I've just created a computer name gomaster. But autogtp cannot connect.

**Comment by Vandertic** [comment]
Are you using sai.hta under Windows or directly autogtp? In the latter case can you paste here the command line (masking your password)?

**Comment by egri-nagy** [comment]
On Ubuntu Linux, compiled as instructed for Leela Zero. I use autogtp directly as instructed on the sai homepage in the build dir. PATH is set properly.

**Comment by amato-gianluca** [comment]
I can see your rejected connection attempts in the log of the server. I wonder if it is a problem of different character sets used in the client and in the server.

**Comment by Vandertic** [comment]
Remember --url http://sai.unich.it/
The last slash / is needed

**Comment by egri-nagy** [comment]
Slash is there.
The encoding is Unicode UTF-8, the compatibility default for the Gnome terminal.
Anything else in the logs?

**Comment by amato-gianluca** [comment]
Could you please try to create a different computername/password combination ?

**Comment by egri-nagy** [comment]
I tried two new combinations. Computer name taichip3 and taichi. Same result. Is the email the problem then?

**Comment by egri-nagy** [comment]
I tried a different email as well. The computer name is rtx2070 this time. Still the same errore message.

**Comment by amato-gianluca** [comment]
I am going to change the code of the server in order to give us more
diagnostic data. Once finished, I will ask you to make more experiments.

**Comment by amato-gianluca** [comment]
I understand what is problem, now!

The --username parameter for autogtp should be filled with you computername (rtx2070, taichi, ...) not your email address. Actually, calling the parameter "username" is misleading, we will fix this in a future revision.

**Comment by egri-nagy** [comment]
Indeed, that was the problem. Sorry for the misunderstanding.

Btw., thank you for this project! I do a lot of game reviews for students, so the 9x9 with variable komi is a great help.
