### ISSUE TITLE
autogtp error of sai-0.17.4-gpu.exe

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#18]
```
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 30 s.
```

the same machine, run autogtp of leelaz is ok

```
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
net: 6ee288bdde21cc080f8be9db33dd179385736cc3852bcc7a2206eaa4a6cf0538.
./leelaz --batchsize=5 --tune-only -w networks/6ee288bdde21cc080f8be9db33dd179385736cc3852bcc7a2206eaa4a6cf0538.gz
Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors
```

**Comment by l1t1** [comment]
I create a user at http://sai.unich.it/user-request
it returns
`OK, an email has been sent to your address. You can now close this window.`
but no email recieved

**Comment by l1t1** [comment]
find the mail at the trash box, i click the link in the email
it returns
`Congratulations! Your account for computer my has been created. You can now close this window.`
then
i run `autogtp  --username myname --password xxxxxxx`
still
```
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 30 s.
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 45 s.
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 67 s.
```

**Comment by Vandertic** [comment]
Probably wrong authentication. Can you create a new user and try again? (it's OK to use the same email, but you have to change the computername)

**Comment by l1t1** [comment]
i created a new user, same problem

**Comment by l1t1** [comment]
`Double-click on sai.hta – authorization for this operation may be requested, if so please grant it`
but i didnot see the file sai.hta  in  sai-0.17.4-gpu.exe.

**Comment by l1t1** [comment]
it works, i found the sai.hta, close the issue

**Comment by Vandertic** [comment]
The file sai.hta must be there.
Moreover, what could be wrong with autogtp from the command line is that you have also to specify --url http://sai.unich.it/
The last slash / is needed

**Comment by l1t1** [comment]
--url http://sai.unich.it/ also works, thanks

**Comment by l1t1** [comment]
my game
```
5363e94683a55bf02d2d4c29e10aff54	5b8725d6	black	170	13.4 minutes ago	8.1 minutes	sgf	you	18	my
```

**Comment by Vandertic** [comment]
Thank you for contributing!
