### ISSUE TITLE
please adjust the x-axis of the graph

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#23]
so that the curve shows in the middle of the graph

**Comment by Vandertic** [comment]
We want to make the progress comparable with LZ, i.e. the grey crosses on the far right. But you can easily zoom in with the mouse wheel.

**Comment by l1t1** [comment]
because the lz nets of samilar strength is about 4 times training games, the curve will become smaller portion and harder to read.

**Comment by Vandertic** [comment]
But you can zoom. Yes?

**Comment by l1t1** [comment]
the gragh is impossible to zoom on android mobile

**Comment by Vandertic** [comment]
Android not zooming I think we can deal with. It would be worst to have LZ nets outside default range, because in that case no one would see them.

**Comment by l1t1** [comment]
the graph of http://lczero.org/ is good to read

**Comment by l1t1** [comment]
how about let sai and lz use different scale ?
eg 1:8, thuse the points and curve will be more readable
