### ISSUE TITLE
what is the range of komi of self-play games?

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#24]
I found 33, it seems too big for regular game.
and is komi value related with the winrate of when load prior games at partial moves?

**Comment by Vandertic** [comment]
There are also much larger komi values. They will become smaller when the network will be stronger

**Comment by l1t1** [comment]
```
Got new job: selfplay
net: 6a9f5d17e18f5593494b94b73995ae62c2b4418eca2138d0e88812f7b875d055.
Engine has started.
Loading 7f5f5ef4f3a64cc2b77f1e4035f8d7a7.sgf with 298 moves
time_settings 0 1 0
Starting GTP commands sent.
Setting komi 51
299 (B G17) 300 (W R18) 301 (B E1) 302 (W R16) 303 (B B16) 304 (W T1) 305
```
I wonder that if komi 51 is ralated with the winrate at move 298?

**Comment by Vandertic** [comment]
It is. This game would be a branch, and the starting point is any previous game position, with the komi that would supposedly make the game from that point fair
