### ISSUE TITLE
the graph lost last net

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#26]
now the current net is 33, but the graph only shows 32
![1](https://user-images.githubusercontent.com/23301704/67742143-2831e200-fa56-11e9-94c1-28f958fabc1a.jpg)

**Comment by l1t1** [comment]
![2](https://user-images.githubusercontent.com/23301704/67742714-c1adc380-fa57-11e9-9b84-0594a7753cd9.jpg)

and i open http://sai.unich.it/static/elo.html in another browser, it only shows 32

**Comment by Vandertic** [comment]
It's manually updated, and I am at CET time it't 7 am :-)
Anyway, thanks for pointing out, just updated! ;-)

(Also, I was trying to quickly train 3 more nets on fewer generations to see if we could get an improvement over 704b

**Comment by Vandertic** [comment]
If the browser doesn't show update information, you should clear the cache
