### ISSUE TITLE
OpenCL.dll missing from release

### ISSUE THREAD

**Issue by iopq** [CuriosAI/sai#32]
I didn't compile from source, I used the installer (which was in Italian for whatever reason)

It did not put the OpenCL.dll into the folder, so the program did not run until I copied the correct one from the LZ folder.

I'm on Intel integrated graphics, Win 8

**Comment by Vandertic** [comment]
Noted.

**Comment by amato-gianluca** [comment]
Can I have more information on this topic? I checked on my PC and it works without OpenCL.dll in the folder. Is this a problem that only shows up in Win 8?

**Comment by iopq** [comment]
It depends on whether it's in the folders that Windows checks for .dll loading.

1. Application folder
2. Current folder
3. Windows folder
4. %PATH%

So if the driver didn't add its folder to the PATH environment variable or put the .dll in the correct windows folder, it won't find it

You can either include it, or release it as a separate download for people who have issues getting it working

**Comment by amato-gianluca** [comment]
Fixed in release 0.17.5.
