### ISSUE TITLE
how to choose the better net when they have same winrate

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#33]
you choose the f3cf6caa not bc82b926 as sai48,
i noticed the first one has 1 draw game and the second has 3

**Comment by l1t1** [comment]
one thing more, 35/54=0.6481 not 0.6574=35.5/54, both of then got 0.6574, why

**Comment by kennyfs** [comment]
Maybe the draw games will be 0.5

l1t1 <notifications@github.com> 於 2019年11月2日 週六 17:00 寫道：

**Comment by l1t1** [comment]
in http://sai.unich.it/match-games/5dbd218f64f5b074ecb43727 and http://sai.unich.it/match-games/5dbd292264f5b074ecb43e59 , they both got 0.6481

**Comment by kennychenfs2** [comment]
Oh, it must be the wrong number because developer didn't handle draw games well.

**Comment by Vandertic** [comment]
True. We will correct the match-games pages. Thank you. And, yes, draw games should count for 0.5 score. 

In the case of a tie, the pipeline _should_ choose the first one of the tying networks, so bc82b926 should have been chosen over f3cf6caa.

I believe maybe, when the networks were compared, f3cf was ahead, and then some additional games arrived after the decision was made.

Anyway, it doesn't really matter much. These matches are just to check that we are not promoting a terrible network.

**Comment by Vandertic** [comment]
Match-games page is now corrected to deal with draws
