### ISSUE TITLE
the graph show different appearance in firefox and edge

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#36]
firefox 56 , the lz scale isn't 1:5
![canvas115](https://user-images.githubusercontent.com/23301704/68168664-8144cd00-ffa4-11e9-804c-419248f77247.png)

edge 79 is ok
![edge115](https://user-images.githubusercontent.com/23301704/68168672-86a21780-ffa4-11e9-9a41-6413db69f2cd.png)

**Comment by l1t1** [comment]
my fault 
I didnt clear the cache, if open a new private window in firefox, it's ok
![canvas115a](https://user-images.githubusercontent.com/23301704/68168867-3e372980-ffa5-11e9-883f-0d37c4e00507.png)

**Comment by l1t1** [comment]
but in zero.sjeng.org, the graph is always refresh without clearing the cache.

**Comment by Vandertic** [comment]
Yes, we need some spare time to write the needed javascript code. SAI has true Bayes-Elo ratings and this complicates things somewhat. We couldn't simply use LZ graph as it was.
