### ISSUE TITLE
a question about candidate net winrate

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#37]
i seldom see nets has very low winrate (below 30%)to current net in leelaz project,
but i often see it in sai project, why?

**Comment by Vandertic** [comment]
I believe one reason is that we always train on a very small set of games. In fact nets play just 4k games each. Progress is quite fast, so we cannot use the games from 20 or more nets, as the difference in strength would be too much. We are currently training on data from the last 12, 8, and 4 generations
