### ISSUE TITLE
The wrong network was promoted.

### ISSUE THREAD

**Issue by Nazgand** [CuriosAI/sai#40]
2019-11-06 06:42    e9c845c5 VS 9df1b56e 42 : 0 : 18 (70.00%)    60 / 50    promotion
2019-11-06 05:39    f40513c4 VS 9df1b56e 38 : 3 : 13 (73.15%)    54 / 50    promotion
f40513c4 has a higher win percentage, yet e9c845c5 was promoted instead.

Perhaps the bug is because e9c845c5 had more wins?
38/54=0.7037, so it seems ties are not the problem, rather just the number of wins seems to be the reason.

**Comment by akdtg** [comment]
At the time when e9c845c5 was promoted it had a better win percent. Since then a few more game were played.

**Comment by Vandertic** [comment]
Exactly. Very low probability event as it needs to happen with the last trained network.
Anyway, with just 50 games and no match between candidates, we are not claiming to be choosing the best candidate, but just a good one
