### ISSUE TITLE
why play some promote match vs prior best nets

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#41]
such as dd3d0acb VS  27a8b38e

**Comment by Vandertic** [comment]
There was a bug in the procedure, and we lost 4 promotion nets. I recovered them and put up tardive promotion matches, just to check that we were not losing a very good network (in which case I would have manually changed the promoted network).

The bug repeated this night and we lost again 4 nets. I corrected the bug minutes ago and now we should be ok. I am not trying to recover the last 4 lost nets though, as the new training started already.

**Comment by l1t1** [comment]
does it mean the number of candidate will increase if a fixed number nets are all weak? i notice sai 68 is picked from 18 nets.

**Comment by Vandertic** [comment]
No. Just some problems with the training procedure
