### ISSUE TITLE
self-play games list show strange weight hash 

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#42]
the 1st game shows xx-4534a
![2019-11-08_091952](https://user-images.githubusercontent.com/23301704/68441445-092b1100-0209-11ea-8254-5b4342e4803d.png)
i opened the sgf, it's normal
`(;GM[1]FF[4]RU[Chinese]DT[2019-11-08]SZ[19]KM[36.5]PB[SAI 0.17 4 4534acc2]PW[SAI 0.17 4534acc2]`

**Comment by Vandertic** [comment]
Cool. You found a game that was purged before training because of wrong parameters. I would guess maybe a visits number different from 1200?
We don't know why, but 1 game every 1000 or so is played with some wrong parameter.
We check and purge them by renaming the hash before training.

**Comment by l1t1** [comment]
got it, thanks
