### ISSUE TITLE
why this komi -15 game has so many moves

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#43]
http://sai.unich.it/view/0b3970297413045660333ee73088f3558bdb077a5884e28166dda0a3e1a1d92c.sgf

**Comment by kennyfs** [comment]
I've seen more.
This game is normal.

l1t1 <notifications@github.com> 於 2019年11月9日 週六 10:08 寫道：

**Comment by kennyfs** [comment]
the datas are based on 40 selfplay games.
sai
move count
mean 310.425
standard division 116.67
lz
mean 209.375
standard division 93.91
So, It's very ordinary for both lz and sai.

陳仲肯 <kenny.kuo.fs@gmail.com> 於 2019年11月9日 週六 10:13 寫道：

**Comment by l1t1** [comment]
i mean, we know kimo 7 is blance, kimo -15 is too big to white side, why didnt white resign eariler?

**Comment by kennyfs** [comment]
sai71 actually think the winrate is 7.34% when 467th move, and it becomes 2.89% when the last move.
1600 visits
So, there is no problem.
