### ISSUE TITLE
elo display

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#44]
Why not show the elos in Best Network Hash table?

**Comment by Vandertic** [comment]
It is linked to the problem with the elo-graph, that is updated manually from remote and not computed directly by the server. I cannot code in javascript. We will upgrade as soon as the javascript-competent in the team has some free time from real life ;-)

**Comment by l1t1** [comment]
a code to convert json into sqlite, from https://www.codeproject.com/Tips/4067936/Load-JSON-File-with-Array-of-Objects-to-SQLite3-On
```
import json
import sqlite3
from datetime import datetime
db=sqlite3.connect('C:/Downloads/sqlite3/myDB.sqlite')
with open('C:/Downloads/elostat1116.json', encoding='utf-8-sig') as json_file:
    json_data = json.loads(json_file.read())
    
#Aim of this block is to get the list of the columns in the JSON file.
    columns = []
    column = []
    for data in json_data:
        column = list(data.keys())
        for col in column:
            if col not in columns:
                columns.append(col)
                                
#Here we get values of the columns in the JSON file in the right order.   
    value = []
    values = [] 
    for data in json_data:
        for i in columns:
            value.append(str(dict(data).get(i)))   
        values.append(list(value)) 
        value.clear()
        
#Time to generate the create and insert queries and apply it to the sqlite3 database       
    create_query = "create table if not exists myTable ({0})".format(" text,".join(columns))
    insert_query = "insert into myTable ({0}) values (?{1})".format(",".join(columns), ",?" * (len(columns)-1))    
    print("insert has started at " + str(datetime.now()))  
    c = db.cursor()   
    c.execute(create_query)
    c.executemany(insert_query , values)
    values.clear()
    db.commit()
    c.close()
    print("insert has completed at " + str(datetime.now())) 
```
then i open the sqlite database file with `C:/Downloads/sqlite3>sqlite3 mydb.sqlite`,  we can get the elo now
```
sqlite> .header on
sqlite> select * from mytable where best='True' order by net+0;
rating|net|sprt|hash|best
0|0|???|g000:daccb7|True
2126.3|4713.021263|PASS|g001:30a4c4|True
2943.8|8359.029438|PASS|g002:f8dd5d|True
3587.5|12246.035875|PASS|g003:9fcadb|True
3848|16143.03848|PASS|g004:a119ea|True
3839.9|19995.038399|PASS|g005:9a1e17|True
3989|24844.03989|PASS|g006:20aee1|True
4360.6|28523.043606|PASS|g007:c0aef3|True
4403.1|32371.044031|PASS|g008:389d81|True
4609.8|36174.046098|PASS|g009:0f3304|True
4776.6|40056.047766|PASS|g00a:53c734|True
4651.5|43915.046515|PASS|g00b:d8d67c|True
```

**Comment by l1t1** [comment]
btw the data josn: http://sai.unich.it/static/elostat.json

**Comment by l1t1** [comment]
a more readable format
```
sqlite> select row_number()over(order by net+0)-1 no, rating,round(rating-lag(rating)over(order by net+0))gap from mytable where best='True' order by net+0 desc;
no|rating|gap
92|9048.6|364.0
91|8684.7|22.0
90|8662.8|3.0
89|8659.5|-8.0
88|8667.3|-27.0
87|8694.1|34.0
86|8659.8|48.0
85|8611.6|20.0
84|8591.7|-19.0
83|8610.5|-16.0
82|8626|99.0
```

**Comment by l1t1** [comment]
all lz compare net
```
sqlite> select * from mytable where hash like '%LZ%';
rating|net|sprt|hash|best
2632.2|53000.026322|TEST|LZ006:a11516|False
3453.7|117000.034537|TEST|LZ009:6f274a|False
4553.6|178000.045536|TEST|LZ013:1607db|False
5592.4|191000.055924|TEST|LZ016:fe7a6c|False
5957.1|194000.059571|TEST|LZ017:5bcb39|False
6085.9|200000.060859|TEST|LZ018:4701bb|False
6614.5|221000.066145|TEST|LZ024:3382a7|False
6954.5|248459.669545|TEST|LZ030:273a02|False
7443.5|272031.474435|TEST|LZ036:c99f1a|False
7762.5|291262.677625|TEST|LZ040:30004a|False
8378.7|335152.283787|TEST|LZ047:830158|False
8812.9|572228.088129|TEST|LZ058:ed002c|False
9016.5|650819.490165|TEST|LZ068:af4f49|False
```

**Comment by l1t1** [comment]
no|rating|gap
-|-|-
96|9279.8|109.0
95|9170.4|35.0
94|9135.4|44.0
93|9091.8|70.0
92|9021.6|356.0
91|8665.9|22.0
90|8644.2|1.0
89|8643.3|-15.0
88|8658.1|-28.0
87|8685.8|36.0
86|8650.2|46.0
85|8604|18.0
84|8585.6|-17.0
83|8602.8|-12.0
82|8614.8|93.0

**Comment by l1t1** [comment]
Nov 22nd

no|rating|gap
-|-|-
110|9638.2|40.0
109|9598.2|20.0
108|9577.8|38.0
107|9540.3|12.0
106|9528|-9.0
105|9536.5|70.0
104|9466.1|82.0
103|9384.5|-38.0
102|9422.6|1.0
101|9421.6|55.0
100|9366.3|85.0
99|9281.5|15.0
98|9266.7|-16.0
97|9282.8|79.0
96|9203.6|135.0
95|9068.3|18.0
94|9049.9|38.0
93|9011.5|55.0
92|8956.3|323.0
91|8633.1|26.0
90|8607.1|-1.0
89|8607.8|-18.0
88|8625.4|-28.0
87|8653.1|39.0
86|8614|43.0
85|8570.9|16.0
84|8554.7|-16.0
83|8570.9|-12.0
82|8582.8|92.0
81|8490.4|15.0

**Comment by Vandertic** [comment]
Elograph with automatic update coming today or tomorrow.

**Comment by l1t1** [comment]
no|rating|gap
-|-|-
122|9887.9|69.0
121|9819.1|-38.0
120|9857.2|44.0
119|9812.9|-2.0
118|9814.7|-11.0
117|9825.8|32.0
116|9794.1|-12.0
115|9805.7|27.0
114|9778.4|35.0
113|9743.9|6.0
112|9738.1|8.0
111|9729.8|0.0
110|9729.6|18.0
109|9711.5|-9.0
108|9720.9|62.0
107|9658.7|11.0
106|9648.1|-2.0
105|9650.4|49.0
104|9601.9|93.0
103|9509.1|-45.0
102|9554.3|5.0
101|9549.8|46.0
100|9503.8|80.0

**Comment by Vandertic** [comment]
Elograph is almost automatically updated, and there are Elo values in the networks table.

**Comment by l1t1** [comment]
nice job

**Comment by l1t1** [comment]
suggest  round the elo value to integer

**Comment by l1t1** [comment]
can you add a flag of 9x192 nets in the elo json file http://sai.unich.it/data/newelograph.json?
such as
{"rating":9574.53,"net":562073.0957453,"sprt":"FAIL","hash":"g07b-a48c","best":false},

**Comment by Vandertic** [comment]
> suggest round the elo value to integer

Good point. Done.

> can you add a flag of 9x192 nets in the elo json

Will do when possible.

**Comment by l1t1** [comment]
the values always change after playing matches, eg. sai 127 was 97xx yesterday, but is 98xx today
yesterday
![2019-11-29_074936](https://user-images.githubusercontent.com/23301704/69835469-e9719080-127c-11ea-8a68-e86109a36b39.png)
today
![2019-11-29_074952](https://user-images.githubusercontent.com/23301704/69835482-f9897000-127c-11ea-83d7-37d239d21068.png)

**Comment by Vandertic** [comment]
This cannot be easily corrected. Elo are always computed using all matches, moreover, they are estimates. Differences between networks should be very similar though

**Comment by l1t1** [comment]
could you adjust to narrow the range, now the 98xx elo has increased to 100xx
