### ISSUE TITLE
Interesting: SAI94 tends to play tengen in high visits.

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#53]
I found sai94 play Tengen on an empty board.
![2019-11-16 18-01-32 的螢幕擷圖](https://user-images.githubusercontent.com/37182101/68991634-97536700-089b-11ea-8050-4aa682ec9ed7.png)
Tengen takes 75.7595725% of 180595 visits, how interesting!

**Comment by kennyfs** [comment]
Also, sai tends to play Tengen after the four corners are occupied.

**Comment by Vandertic** [comment]
Interesting analysis!

**Comment by Vandertic** [comment]
Interesting analysis!

**Comment by trinetra75** [comment]
I believe it has been like this for a while: in more than a few games played on [OGS](https://online-go.com/player/695086) Sai with black started with the Tengen...

**Comment by barrtgt** [comment]
I remember there was a period when LZ had a preference for tengen around the same time it started to play ladders a lot.
