### ISSUE TITLE
sai.unich.it cannot visits

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#54]
Can you check it?

**Comment by RosaMGini** [comment]
Sorry guys, the machine is down, possibly due to power loss, out of our control. Hopefully everything will restart early tomorrow morning, we'll keep you posted.  Apologies!

Rosa

**Comment by RosaMGini** [comment]
The system is up again, I'm reopening the issue just to let you know what happened. A power outage took place yesterday night. When power was restored, the system did not restart. We are now investigating why, so that this does not happen again. Apologies!

Rosa
