### ISSUE TITLE
sai 100 has too many candidate nets

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#55]
more than 20 now

**Comment by Vandertic** [comment]
Sorry about that. It was a "quenched" training, with a drop in the learning rate. As such we need some more tests to assess if the step numbers are still ok. This will happen every fourth net, until we reach a good learning rate.

Rate was wrongly 0.05 until net 91. Then we dropped it to

0.01 at net 92
0.004 at net 96
0.002 at net 100
0.001 at net 104

Also, sorry if I was not responding in the last few days, but I had a conference yesterday.

**Comment by l1t1** [comment]
thanks
