### ISSUE TITLE
when sai load a lz net, what the default komi is

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#57]
7.0 or 7.5?
if it is 7.0, as lz nets are train with komi 7.5, will the net strengh drop down?
so if sai100 beat sai load lz58, but it cannot beat leelaz load lz58

**Comment by Vandertic** [comment]
Should be 7.5. You can check with the command heatmap iirc

**Comment by Vandertic** [comment]
I confirm this. Do not even need the command. It's in the status display

**Comment by l1t1** [comment]
got it, also see at http://sai.unich.it/match-games/5dd42f27b451ba7909430917
