### ISSUE TITLE
Failing to resign?

### ISSUE THREAD

**Issue by barrtgt** [CuriosAI/sai#58]
Not sure if I'm missing something, but after a ladder is captured by the other player, and the winrate is 0%, sai refuses to resign for me in this game:

(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.43.3]KM[7.5]SZ[19]DT[2019-11-20]PB[sai 0.17.4 10kv]SBKV[49.09];B[pc];W[pp]SBKV[48.63];B[dd];W[dp]SBKV[47.62];B[cp];W[cq]SBKV[46.58];B[co];W[do]SBKV[46.86];B[cn];W[dq]SBKV[46.58];B[ck];W[dm]SBKV[47.44];B[cm];W[qe]SBKV[47.55];B[qd];W[pe]SBKV[47.23];B[nc];W[cc]SBKV[49.59];B[cd];W[dc]SBKV[49.25];B[ec];W[eb]SBKV[49.4];B[fb];W[fc]SBKV[49.32];B[ed];W[gb]SBKV[49.41];B[db];W[fa]SBKV[49.4];B[cb];W[kq]SBKV[53.21];B[qq];W[qp]SBKV[53.26];B[pq];W[nq]SBKV[50.95];B[nr];W[mr]SBKV[52.17];B[or];W[rq]SBKV[51.56];B[op];W[ro]SBKV[57.46];B[mq];W[mp]SBKV[57.39];B[lq];W[lr]SBKV[56.77];B[lp];W[lo]SBKV[77.84];B[kp];W[jp]SBKV[80.93];B[ko];W[kn]SBKV[84.81];B[jo];W[io]SBKV[84.35];B[jn];W[jm]SBKV[89.8];B[in];W[hn]SBKV[90.24];B[im];W[il]SBKV[94.36];B[hm];W[gm]SBKV[95.79];B[hl];W[hk]SBKV[96.17];B[gl];W[fl]SBKV[97.36];B[gk];W[gj]SBKV[97.29];B[fk];W[ek]SBKV[97.63];B[fj];W[fi]SBKV[97.53];B[ej];W[dj]SBKV[97.32];B[ei];W[eh]SBKV[98.19];B[di];W[ci]SBKV[98.69];B[dh];W[dg]SBKV[23.73];B[ch];W[bh]SBKV[18.13];B[cg];W[cf]SBKV[43.42];B[bg];W[ag]SBKV[16.7];B[bf];W[be]SBKV[18.56];B[dk];W[af]SBKV[0];B[bc])

I ran it in sabaki with this command: 
-g -w 6fd8b5494da59287528c31c0d9370637edf5ff16111bc2d19897f486bd8a280a.gz --noponder -p 0 -v 10000 --komi 7.5 --lambda 0 --mu 0 -r 20 -t 6 --batchsize 3 --nrsymm --timemanage off --precision single --puct 0.75 --softmax_temp 0.75 -m 10

and time_settings 0 1 0

This was for the position right after capture:

lz-genmove_analyze B 100
= info move (…)
play B17
Debug...
Thinking at most 2678400.0 seconds...
NN eval=0.000000. Agent eval=0.000000
cpus=6
Playouts: 5550, Win:  0.00%, PV: B17 Q11 S2 T2 B3 B2 A3 A2 B4 N16 O16
 B17 ->    5407 (V:  0.00%) (LCB:  0.00%) (N: 54.04%) (A: -144.0) PV: B17 Q11 S2 T2 B3 B2 B4 N14 Q10 R10
 B16 ->    1833 (V:  0.00%) (LCB:  0.00%) (N: 18.30%) (A: -144.9) PV: B16 Q11 B3 B2 S2 T2 B4 N16 Q10 P11
  S2 ->     838 (V:  0.00%) (LCB:  0.00%) (N:  8.35%) (A: -146.0) PV: S2 B17 T3 S4 P3 P5 B3 B2 R11
  B3 ->     498 (V:  0.00%) (LCB:  0.00%) (N:  4.95%) (A: -148.9) PV: B3 B17 S2 T2 R11 B2 R8 N15
 R11 ->     220 (V:  0.00%) (LCB:  0.00%) (N:  2.19%) (A: -147.3) PV: R11 B17 B3 B2 S2 T2 R8 N15 M16
 Q12 ->     200 (V:  0.00%) (LCB:  0.00%) (N:  1.99%) (A: -145.2) PV: Q12 B17 B3 B2 S2 T2 A3 Q10
 Q11 ->     146 (V:  0.00%) (LCB:  0.00%) (N:  1.44%) (A: -144.6) PV: Q11 B17 S2 T2 B3 B2 A3 R12 R11
 R10 ->      98 (V:  0.00%) (LCB:  0.00%) (N:  0.99%) (A: -145.3) PV: R10 B17 S2 T2 B3 R12 P11
 R12 ->      87 (V:  0.00%) (LCB:  0.00%) (N:  0.86%) (A: -146.4) PV: R12 B17 S2 T2 B3 B2 B4
 Q10 ->      62 (V:  0.00%) (LCB:  0.00%) (N:  0.59%) (A: -143.8) PV: Q10 B17 S2 T2 B3 R12 R11
  D6 ->      42 (V:  0.00%) (LCB:  0.00%) (N:  0.43%) (A: -153.1) PV: D6 B17 S2 T2 B3 B2
 H17 ->      26 (V:  0.00%) (LCB:  0.00%) (N:  0.24%) (A: -148.9) PV: H17 B17 S2 T2
  R9 ->      24 (V:  0.00%) (LCB:  0.00%) (N:  0.23%) (A: -148.5) PV: R9 B17 S2 T2 R12 B4
 P12 ->      20 (V:  0.00%) (LCB:  0.00%) (N:  0.19%) (A: -147.1) PV: P12 B17 S2 T2 B3
 Q13 ->      20 (V:  0.00%) (LCB:  0.00%) (N:  0.18%) (A: -148.3) PV: Q13 Q11 B17 P13 S2 T2
  B4 ->      16 (V:  0.00%) (LCB:  0.00%) (N:  0.17%) (A: -150.5) PV: B4 B17 S2 T2 R11
 O12 ->      15 (V:  0.00%) (LCB:  0.00%) (N:  0.13%) (A: -149.9) PV: O12 B17 B3 B2 S2
 P11 ->      15 (V:  0.00%) (LCB:  0.00%) (N:  0.14%) (A: -144.8) PV: P11 B17 B3 R11 S2
  R8 ->      13 (V:  0.00%) (LCB:  0.00%) (N:  0.12%) (A: -148.0) PV: R8 B17 R11 B4
 K17 ->      13 (V:  0.00%) (LCB:  0.00%) (N:  0.13%) (A: -151.2) PV: K17 B17 S2 T2 B3
 O13 ->      13 (V:  0.00%) (LCB:  0.00%) (N:  0.13%) (A: -146.5) PV: O13 B17 S2 T2
 R13 ->      12 (V:  0.00%) (LCB:  0.00%) (N:  0.10%) (A: -145.6) PV: R13 R11 B17 Q13
 F16 ->      12 (V:  0.00%) (LCB:  0.00%) (N:  0.08%) (A: -146.4) PV: F16 B17 G17
 A17 ->      12 (V:  0.00%) (LCB:  0.00%) (N:  0.13%) (A: -147.2) PV: A17 R11 B3
  Q9 ->      11 (V:  0.00%) (LCB:  0.00%) (N:  0.11%) (A: -144.5) PV: Q9 B17 R12
 N13 ->      11 (V:  0.00%) (LCB:  0.00%) (N:  0.12%) (A: -149.6) PV: N13 B17 R11
 G16 ->      11 (V:  0.00%) (LCB:  0.00%) (N:  0.07%) (A: -149.9) PV: G16 R11 B17
 L17 ->      11 (V:  0.00%) (LCB:  0.00%) (N:  0.10%) (A: -148.6) PV: L17 B17 B3 B2
 O11 ->       9 (V:  0.00%) (LCB:  0.00%) (N:  0.07%) (A: -146.6) PV: O11 B17 S2
 P10 ->       9 (V:  0.00%) (LCB:  0.00%) (N:  0.08%) (A: -146.6) PV: P10 B17 B3
 P13 ->       8 (V:  0.00%) (LCB:  0.00%) (N:  0.08%) (A: -146.5) PV: P13 R12 B17
  Q7 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -148.0) PV: Q7 B17
 L16 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.04%) (A: -148.5) PV: L16 Q12
 O14 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.05%) (A: -148.5) PV: O14 B17
 O10 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -147.4) PV: O10 B17
 J17 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.07%) (A: -150.5) PV: J17 B17 S2
  R7 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -146.5) PV: R7 Q10
  P8 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -147.3) PV: P8 B17
 M13 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.04%) (A: -148.1) PV: M13 B17
 B18 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.08%) (A: -150.2) PV: B18 R11
 S10 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -145.8) PV: S10 R11
 A19 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -159.8) PV: A19 B17
 B10 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.08%) (A: -151.1) PV: B10 B17
 L14 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -148.7) PV: L14 B17
 A18 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -153.0) PV: A18 Q10
 N12 ->       7 (V:  0.00%) (LCB:  0.00%) (N:  0.06%) (A: -148.4) PV: N12 B17
  R6 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -148.2) PV: R6 R8
 S12 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -148.1) PV: S12 B17
 H15 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -149.5) PV: H15 B17
  P6 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -145.6) PV: P6 B17
  Q5 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -144.4) PV: Q5 B17
  P9 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -147.6) PV: P9 B17
 N14 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.04%) (A: -145.8) PV: N14 B17
 H16 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.05%) (A: -148.1) PV: H16 Q10
 K15 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -148.6) PV: K15 B17
 S11 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -147.5) PV: S11 B17
  D8 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.04%) (A: -152.4) PV: D8 B17
 K16 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.07%) (A: -147.2) PV: K16 B17
 A16 ->       6 (V:  0.00%) (LCB:  0.00%) (N:  0.05%) (A: -153.3) PV: A16 Q11
 J16 ->       5 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -150.1) PV: J16 B17
  Q8 ->       5 (V:  0.00%) (LCB:  0.00%) (N:  0.06%) (A: -146.2) PV: Q8 B17
 G17 ->       5 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -150.4) PV: G17 B17
 N15 ->       4 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -149.8) PV: N15 B17
 B19 ->       3 (V:  0.00%) (LCB:  0.00%) (N:  0.03%) (A: -157.6) PV: B19 B17
 E19 ->       2 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.5) PV: E19 D19
  T6 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -156.8) PV: T6 
 T10 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -157.0) PV: T10 
 T11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.8) PV: T11 
  P7 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -152.6) PV: P7 
  Q6 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -157.9) PV: Q6 
 H12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.6) PV: H12 
 J13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.5) PV: J13 
  O7 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.0) PV: O7 
 M11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.6) PV: M11 
 L12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -156.8) PV: L12 
 G12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -154.6) PV: G12 
 J14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -147.9) PV: J14 
  S7 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -148.0) PV: S7 
  O9 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -157.6) PV: O9 
  A5 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.4) PV: A5 
 P14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -145.4) PV: P14 
  O8 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -148.3) PV: O8 
 J12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -159.5) PV: J12 
 G13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.8) PV: G13 
 L15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -149.3) PV: L15 
  T4 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.0) PV: T4 
  S9 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -157.4) PV: S9 
  S1 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.9) PV: S1 
  S8 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -147.4) PV: S8 
 M15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -156.1) PV: M15 
  A9 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -153.2) PV: A9 
  A1 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -164.1) PV: A1 
  T3 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.2) PV: T3 
 H18 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -153.3) PV: H18 
 A11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -166.0) PV: A11 
 S13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -148.4) PV: S13 
 K12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -149.5) PV: K12 
 H19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -152.7) PV: H19 
  Q1 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -160.2) PV: Q1 
 G19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -165.9) PV: G19 
 E14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -160.0) PV: E14 
 M17 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -157.3) PV: M17 
 M12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -158.0) PV: M12 
 M14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -145.7) PV: M14 
 S15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -147.7) PV: S15 
 H14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -151.8) PV: H14 
  B9 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -153.7) PV: B9 
 G14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -152.5) PV: G14 
 E10 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -167.0) PV: E10 
  A4 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.5) PV: A4 
 B11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -157.5) PV: B11 
  T8 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -163.3) PV: T8 
 A15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -170.2) PV: A15 
 C12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -168.5) PV: C12 
 D12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -167.9) PV: D12 
 A12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.2) PV: A12 
 C19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -165.0) PV: C19 
 M19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -162.6) PV: M19 
 J15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -155.6) PV: J15 
  B8 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -161.9) PV: B8 
  A6 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -159.6) PV: A6 
 B14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -166.6) PV: B14 
 N10 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.2) PV: N10 
  T5 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -153.7) PV: T5 
 B13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -170.2) PV: B13 
 L13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -156.3) PV: L13 
 J19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -153.7) PV: J19 
 F15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -157.8) PV: F15 
 K13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -150.1) PV: K13 
 K18 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.2) PV: K18 
 D11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -161.8) PV: D11 
 D19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -153.8) PV: D19 
 O15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -156.4) PV: O15 
 K19 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -167.4) PV: K19 
 K14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -156.0) PV: K14 
 T12 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -151.1) PV: T12 
  K1 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -173.1) PV: K1 
 N11 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -154.8) PV: N11 
 A10 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.3) PV: A10 
 G15 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -154.6) PV: G15 
  T9 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -161.2) PV: T9 
  S6 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -155.9) PV: S6 
 M16 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -156.0) PV: M16 
 D14 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -164.8) PV: D14 
 H13 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -158.9) PV: H13 
 J18 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.02%) (A: -154.9) PV: J18 
  T7 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -166.8) PV: T7 
  T1 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -164.7) PV: T1 
  A8 ->       1 (V:  0.00%) (LCB:  0.00%) (N:  0.01%) (A: -162.6) PV: A8 
6.3 average depth, 13 max depth
4851 non leaf nodes, 2.06 average children
10004 visits, 2932524 nodes, 10003 playouts, 2258 n/s

After messing around with it a bit more it does the same thing with LZ and resigns after a few more moves, So it is probably working as intended? I will close the issue for now.

**Comment by Vandertic** [comment]
I can't see the move number. Maybe it's less than 92? LZ won't resign before 361/4 moves. SAI does the same

**Comment by barrtgt** [comment]
Yep, that was it!
