### ISSUE TITLE
Cpu becomes a bottleneck for autogtp, is there some issue?

### ISSUE THREAD

**Issue by nanzi** [CuriosAI/sai#60]
My recent amd cpu is in full load while gpu usage is only 20%, intel cpu users complains it in the same(They have 16cores recent cpus or so). I have tested as -g2 works fastest on my laptop and -g4 make my cpu crazy while gpu never jumps over 30%. Why cpu becomes a  bottleneck?

Hope SAI becomes better, and wish you have a good day!

**Comment by Vandertic** [comment]
It should be identical to LZ from this point of view. Generally, on my computer I use -g strictly less the number of cores, though. I agree that -g4 with 4 cores slows the pc considerably

**Comment by l1t1** [comment]
i can run validation -g2 with --sai --sai on i5-6600+8G+GT730-2G win7 ok
but though i can run  validate -g2 on i7-8700+32G+quadro P620-2G win 10 at first, it always fails after some games

**Comment by l1t1** [comment]
but i can run autogtp -g6  on i7-8700 ok
