### ISSUE TITLE
sai#125 won Zen9d by Lizzie.

### ISSUE THREAD

**Issue by atoutw** [CuriosAI/sai#62]
Just for your reference.

![2019-11-28 021415](https://user-images.githubusercontent.com/43053753/69745482-9f59b380-1185-11ea-9308-59c1ec6909b6.jpg)

But because weak ladder, sai often lose to gtp4zen by sabaki.

**Comment by Vandertic** [comment]
Cool!
BTW in a couple of weeks we will add an option to SAI to help the search with ladders.

**Comment by Splee99** [comment]
> 
> 
> Cool!
> BTW in a couple of weeks we will add an option to SAI to help the search with ladders.

That will be great. SAI is quite strong right now except it has almost no knowledge about ladders.

**Comment by Vandertic** [comment]
The problem with ladders is tougher than I thought. Even if we encourage exploration of the ladder, SAI always thinks that it is favorable to the player which is receiving it. We will need some more time to understand how to solve this issue

**Comment by cryptsport** [comment]
@Vandertic But if you do it like in KataGo? or do you want to find your solution?
https://lifein19x19.com/viewtopic.php?p=247091#p247091

**Comment by Vandertic** [comment]
It is very difficult to reproduce what KataGo does without restarting the run from scratch, as the recent KataGo runs have the "capturable by ladder" as an input feature. We are trying a somewhat softer approach, by tweaking MCTS to encourage exploration of ladders.

**Comment by thynson** [comment]
I think the simple way to boost the net to learn ladder is to add more noise to atari point.

**Comment by Vandertic** [comment]
@thynson can you explain more your idea? I would have thought to do something opposite...

**Comment by Splee99** [comment]
I'm not very familiar with Katago, but from its source code, there is a function called searchIsLadderCaptured(Loc loc, bool defenderFirst, vector<Loc>& buf) in board.cpp. So to my understanding its not about the way of training, but a hard coded rule. Is it used as an input feature or just used in the search? Sorry I'm confused.

**Comment by thynson** [comment]
> @thynson can you explain more your idea? I would have thought to do something opposite...

To let netowrk learn the concept of ladder, we need to produce selfplay games that contains ladder run.
From what I remembered, the time ladder appears on leelazero's selfplay is around 50th leela zero network.
On the other hand, early leelazero networks as well as current sai networks give very low policy on ladder. 
Through not a strict conclusion, I believe that without helps from other technique, we can only wait at some day the self play noise hit on ladder run and sampled when training. I guess it will happens around 1M~2M selfplay, if using AlphaGoZero's noise parameters. 
To boost that process, what we can try is
1. Let some self selfplay starts at position of ladder run. It should be very simple since sai is already able to start selfplay from a given position. but human intervention get involved.
2. Increase the policy of ladder run(which is what I mean in the above post). But I suspect that may harms the policy head.

**Comment by Vandertic** [comment]
Thank you, now it is clear.
We did some analysis on the way SAI mistakes ladders. (By the way, SAI has a very useful 'eval' command that can be used to understand what went wrong in its reasoning. There is a small bug that hampers its workings in the current release, but a subsequent [commit](https://github.com/sai-dev/sai/commit/9ad588b317250900cc8771b98c8615db289f6116) on [next17](https://github.com/sai-dev/sai/commits/next17) branch corrects the problem.)

Before exploration SAI currently strongly believes that all ladders are broken. Suppose black is taken in a working ladder. The network will give high policy to black following the ladder and to white taking less damage from it, hence at some point white will try to give atari from the "wrong" side or put a stone not directly in contact with black, but at some intersections from it (a sort of ladder breaker). The right move for white (the atari in the right direction) gets high policy nonetheless, but not the highest. Exploration is not very deep, but expands on white trying different things to avoid ladder.

The value estimate make things worse, in fact the ladder shape is very thick for black and has a lot of cuts for white, so exploration is sent away from ladder as much as possible. Even if you encourage the ladder exploration, there is simply no way a medium to long ladder can be read in this way. Even for very high visits. (In fact very high visits make things worse.)

Yesterday we pushed a branch [ladders](https://github.com/sai-dev/sai/commits/ladders) that has a couple of small tweaks to improve ladders exploration a bit. You will find that they are not nearly enough, but, if the ladder is short, there are some improvements.

To learn ladders by examples should be difficult to impossible without dedicated input features. In fact the ladder outcome is non-local and subtle, so the network should have millions of examples to stand a chance to learn by itself.

On the other hand, with a dedicated input feature **and** ladder exploration encouraged, it should be able to learn quite quickly.

This can be done in SAI, but it is quite a lot of work, so maybe in the next few months.

@Splee99 I think KataGo function is used to compute the input feature, as in the original AlphaGo.

**Comment by Splee99** [comment]
@Vandertic Thanks. That's a very comprehensive analysis.

**Comment by Splee99** [comment]
Just compiled the ladder branch on Windows. From a 3 handicap game with Hiratuka, it seems that SAI likes to attack with failed ladder, something like ELF does.

[failed-ladder-attack.sgf.txt](https://github.com/sai-dev/sai/files/3965275/failed-ladder-attack.sgf.txt)
![ladder](https://user-images.githubusercontent.com/35020997/70867116-7cb9ef80-1f26-11ea-95f5-d74038c23a05.png)
