### ISSUE TITLE
On the choice of self-play hyper-parameters.

### ISSUE THREAD

**Issue by Vandertic** [CuriosAI/sai#64]
I have spent the last days in doing some math with **c_puct**, **visits** and **policy_temperature**, and I have come up with a nice model for computing the asymptotic policy of the best move.

Asymptotic in the sense of "after many generation with almost stable winrate estimates".

I recall that without changing the **policy_temperature**, the limit is always 100% policy to the move with the best winrate, even if this winrate is almost equal to the second best.

The following plot shows what happens for 2400 visits with puct=1.

<img width="600" alt="uct_thm2" src="https://user-images.githubusercontent.com/27057329/69855798-91db2100-128c-11ea-8b35-78bfe13ed0d7.png">

In SAI we also have a **hard cap at 0.75** for the visits (and hence for the policy) of any move, up to move 30 (same number as random_moves). So for SAI you should add a hard cap at 0.75 for all the above lines.

This said, it is not clear to me if we should change the temperature from its current value of 1.2.

In principle, thanks to the cap, we could also bring back temperature to 1 or so, because policy of the first moves would still not concentrate too much. This would produce stronger self-play games, and hence generally improve the value.

On the other hand, we could also use larger values, to make exploration larger and reduce blind spots.

Comments, opinions and suggestions are much welcome.

**Comment by Glrr** [comment]
Blind spots are the main weakness of strong engines. I think it is worth trying to reduce them, even if it slow down the progression a bit. Of course, if the progression is clearly stuck it could be necessary to reduce the temp.

**Comment by l1t1** [comment]
when will sai 6x128 net better than best lz 6x128?

**Comment by Glrr** [comment]
It could be the right time for trying a slight decrease of the temp.

**Comment by barrtgt** [comment]
I missed when sai switched from -m 50 as well as cpuct change.

**Comment by Vandertic** [comment]
> I missed when sai switched from -m 50 as well as cpuct change.

Thanks for asking, @barrtgt. The puct change (starting from SAI124) was motivated by the increased number of visits (v=2400 starting from SAI119), and some simulations/mathematical considerations by Naphtalin on Discord and myself.

![image](https://user-images.githubusercontent.com/27057329/70538442-5e3ca880-1b62-11ea-9dc2-7e4e508f41c9.png)

The drop in the random_count value (starting from SAI98) was due to the fear that it could be one of the reason behind the difficulty in progress. (Which was actually because of [wrong training rate](https://github.com/sai-dev/sai/issues/34#issuecomment-554422326).)
