### ISSUE TITLE
I compared sai's search result in an empty board with lz's.

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#65]
I ran sai130 and lz254 in an empty board with high visits.
I made the result in an image.
lz is the left one.
![image](https://user-images.githubusercontent.com/37182101/69896819-3f7a2d00-137e-11ea-9117-db75bedb35cd.png)
The following image shows 1e-1 to 1e-5(a move/total)
![image2](https://user-images.githubusercontent.com/37182101/69896876-f676a880-137e-11ea-8e14-5549d7a94e7d.png)

**Comment by dbosst** [comment]
Not sharp at all. I wonder why that is, and if it's good or bad long term.

**Comment by kennyfs** [comment]
sai still doesn't rule out die out the moves around ten-yen. Maybe it would gather in corner later. Or maybe it's because some special settings, I don't know.

**Comment by iopq** [comment]
It's because of higher temperature. As training goes on it should converge, but much later

**Comment by trinetra75** [comment]
> 
> It's because of higher temperature. As training goes on it should converge, but much later

Also please be aware that currently Sai is comparable in strength only to LZ81 [Elo: 8153] and LZ254 [Elo: 15507] is in an entire new dimension :)

**Comment by Vandertic** [comment]
High temperature and hard cap at 75% visits for any single moves were chosen to **avoid** too much concentration on a single move in fuseki.
