### ISSUE TITLE
is the client number in past hour wrong

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#66]
SAI is derived from Leela Zero 0.17 + AutoGTP v18.

49 clients in past 24 hours, 0 in past hour.
603106 total self-play games (6683 in past 24 hours, 0 in past hour).
139464 total match games (1587 in past 24 hours, 147 in past hour).

**Comment by Glrr** [comment]
At that time, all clients were playing match games. It seems that only clients that play selfplay games are counted here.

**Comment by Vandertic** [comment]
I confirm that

**Comment by amato-gianluca** [comment]
I think it has been fixed when we have introduced the leaderboard. If it is not, feel free to reopen the bug.
