### ISSUE TITLE
shall we update the flag of 9x192 net

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#71]
now both failed and passed nets  show same green triangle

![2019-12-05_082639](https://user-images.githubusercontent.com/23301704/70199959-10810400-174e-11ea-95cb-c2f938912ef4.png)

**Comment by Vandertic** [comment]
I agree. I believe it will be done in a few days.

**Comment by amato-gianluca** [comment]
Done, just waiting to reach production.

**Comment by Vandertic** [comment]
Done. Refresh cache if you see wrong colors.
![image](https://user-images.githubusercontent.com/27057329/70266032-fa019980-179b-11ea-8407-721613ef34db.png)

**Comment by l1t1** [comment]
the graph shows different color in firefox and ms-edge, both browsers use private mode, so no cache.
firefox
![2019-12-06_080131](https://user-images.githubusercontent.com/23301704/70284405-d3287f00-17fe-11ea-87e3-8744a92a34a9.png)

ms-edge
![2019-12-06_080214](https://user-images.githubusercontent.com/23301704/70284408-d885c980-17fe-11ea-9fee-95323703fef8.png)

**Comment by amato-gianluca** [comment]
The colors you see in Firefox seem to be wrong. Try refreshing the cache (i.e., clicking on the reload button while the shift  key is down, at least in Linux).

**Comment by l1t1** [comment]
it is ok on firefox now
