### ISSUE TITLE
Ensure a minimum playout per move in selfplay?

### ISSUE THREAD

**Issue by thynson** [CuriosAI/sai#76]
Different from AlphaGo Zero as well as others, leela zero limits the visit in self play games. This indeed improve the speed of selfplay, but some people (including myself) have argued with gcp that, such apporach will result in effect of the noise be reduced, especially in some forced sequences.
To ensure the move founded by noise gains enough visits, we could just let selfplay games ensures a minimum playout in each move. 
I've made an [PR] to leelazero to support flags like `-p 200 -v 1200` or `-p 400 -v 1600`, but not got merged by gcp. Could you please reconsider about it?

[PR]: https://github.com/leela-zero/leela-zero/pull/2158

**Comment by Vandertic** [comment]
I will consider this with collaborators. But notice that the properties and statistics for the visits distribution depends on the total visits number in a nonlinear way (in that visits tends to concentrate more and more on the best move), so we must ensure that the number of visits does not change too much.
Edit: anyway, SAI uses a hard cap on the number of visits of a single move in self-plays (75%) so it suffers less of the problem you raise.

**Comment by thynson** [comment]
>But notice that the properties and statistics for the visits distribution depends on the total visits number in a nonlinear way...

Exactly. So we need some minimum play out to to change the visits of affected node to fit the change of their UCT value.

**Comment by thynson** [comment]
> Edit: anyway, SAI uses a hard cap on the number of visits of a single move in self-plays (75%) so it suffers less of the problem you raise.

Okay, I think that would be enough, since the most picky noise is up to 0.25. But, doesn't it have any bad effect on policy head?

**Comment by trinetra75** [comment]
> 
> 
> > Edit: anyway, SAI uses a hard cap on the number of visits of a single move in self-plays (75%) so it suffers less of the problem you raise.
> 
> Okay, I think that would be enough, since the most picky noise is up to 0.25. But, doesn't it have any bad effect on policy head?

The cap is there only for the moves with random selection (as of now the first 30).

**Comment by Vandertic** [comment]
@thynson We are willing to include your PR, if you can modify it in this way: instead of modifying the behaviour of `-p`, add a new argument `--min_playouts` and keep separate the concepts of `-p` (max playouts, weakens the engine) and minimum playouts with the opposite meaning.

**Comment by thynson** [comment]
Okay, will do it when time available.
