### ISSUE TITLE
a guess about true strength of a promoted net

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#78]
if the same genarate nets average  winrates vs the prior promote nets is near its winrates, then it is accurate.
eg. the winrate of sai 139, all nets of that genarate have a winrate near 80%

**Comment by l1t1** [comment]
eg. the winrate of sai 163, many nets of that genarate have a winrate near 30%

win | all |winrate of 162
-- | -- | --
29.5 | 58 |  
28.5 | 56 |  
34.5 | 58 |  
28 | 58 |  
27 | 58 |  
34.5 | 58 |  
34 | 57 |  
31 | 57 |  
27 | 58 |  
28.5 | 58 |  
28.5 | 58 |  
25.5 | 59 |  
34 | 59 |  
31 | 53 |  
32 | 58 |  
27 | 58 |  
27 | 58 |  
32.5 | 58 |  
482 | 923 | 0.52221

win | all |winrate of 163
-- | -- | --
8.5 | 55 |  
17 | 57 |  
17 | 55 |  
8 | 59 |  
29 | 58 |  
24.5 | 52 |  
26.5 | 57 |  
32 | 56 |  
33.5 | 58 |  
28.5 | 53 |  
27 | 59 |  
23 | 56 |  
30 | 58 |  
21.5 | 59 |  
23.5 | 57 |  
28 | 58 |  
377.5 | 907 | 0.416207

win | all |winrate of 164
-- | -- | --
31 | 58 |  
29 | 59 |  
31.5 | 58 |  
28 | 58 |  
37 | 59 |  
36 | 58 |  
26 | 56 |  
25.5 | 57 |  
31 | 58 |  
32 | 58 |  
28.5 | 58 |  
29 | 58 |  
18 | 58 |  
29.5 | 58 |  
25.5 | 59 |  
32 | 57 |  
469.5 | 927 | 0.506472

win | all |winrate of 165
-- | -- | --
28 | 59 |  
27 | 53 |  
34 | 59 |  
34.5 | 59 |  
30.5 | 58 |  
31 | 59 |  
30 | 58 |  
29 | 53 |  
30.5 | 58 |  
35 | 59 |  
35 | 58 |  
35 | 59 |  
28.5 | 59 |  
33.5 | 58 |  
30 | 57 |  
28 | 58 |  
499.5 | 924 | 0.540584

win | all |winrate of 166
-- | -- | --
31.5 | 59 |  
26.5 | 59 |  
32.5 | 57 |  
33.5 | 59 |  
34 | 56 |  
24 | 58 |  
29 | 59 |  
27.5 | 58 |  
36.5 | 59 |  
23 | 58 |  
36 | 59 |  
27.5 | 59 |  
31 | 59 |  
21 | 59 |  
25.5 | 58 |  
25.5 | 57 |  
464.5 | 933 | 0.497856

win | all |winrate of 167
-- | -- | --
31.5 | 59 |  
23 | 58 |  
30 | 59 |  
32.5 | 59 |  
34 | 59 |  
32 | 59 |  
19.5 | 59 |  
27.5 | 59 |  
32.5 | 54 |  
37 | 57 |  
35.5 | 59 |  
29 | 58 |  
34 | 58 |  
30 | 58 |  
27.5 | 59 |  
35.5 | 57 |  
491 | 931 | 0.52739

**Comment by Vandertic** [comment]
It would be right if the candidate networks were always done the same way. Actually we use candidate nets to test training parameters. For example those nets with very low winrate in generation 163 were trained with a particularly high learning rate, and that way we learned that we need to use lower values.
