### ISSUE TITLE
what is the aim of those refer matches of lz nets themselves

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#81]
2019-12-17 10:04	ae205d8b

 VS  b7768081

0 : 0 : 0	0 / 40	reference
2019-12-17 10:04	5e8f3a94

 VS  ae205d8b

0 : 0 : 2 (0.00%)	2 / 40	reference
2019-12-17 10:02	3e420ffc

 VS  b7768081

0 : 0 : 5 (0.00%)	5 / 10	comparison
2019-12-17 10:02	3e420ffc

 VS  ae205d8b

1 : 0 : 9 (10.00%)	10 / 10	comparison
2019-12-17 10:02	3e420ffc

 VS  5e8f3a94

9 : 0 : 2 (81.82%)	11 / 10	comparison

**Comment by Vandertic** [comment]
Just to better anchor the Elo of LZ nets: until now they only played against different SAI networks, but never one against the other.
