### ISSUE TITLE
can you arrange a match of difference visits

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#83]
just like i did in https://github.com/sai-dev/sai/issues/47

BTW: sai 170 is the first net that run with visits 400 better than lz 250 visit 1

**Comment by Vandertic** [comment]
With autogtp it is not possible to set different visits for the two players.

**Comment by l1t1** [comment]
you can add a option to autogtp, just like url and username

**Comment by Hersmunch** [comment]
https://github.com/leela-zero/leela-zero/pull/2078 ?

Edit: I didn't have a lot of time earlier to explain but I've now double checked the SAI code and it does include the LZ code that allows different options for black and white in an autogtp match. I'm not aware of this ever being used though :)

**Comment by Vandertic** [comment]
Thank you @Hersmunch I wasn't aware of this possibility.
Anyway, from the server side there is work to be done to really implement this feature.

@l1t1 what kind of matches you think we should use this for? I did not understand your point very well before.

**Comment by kennyfs** [comment]
It can be used in the matches which the nets aren't in the same size or sai vs LZ.

**Comment by l1t1** [comment]
eg sai 17x v2400 vs lz157 v1600

**Comment by Vandertic** [comment]
@kennychenfs SAI vs LZ we are performing every promotion or two, at same visits, but with old LZ nets.
@l1t1 I don't quite see the point. We are still way behind LZ107 at same visits so It seems soon to play against LZ157, moreover what information we get exactly by decreasing LZ visits?

**Comment by l1t1** [comment]
the point is to describle the new net with a well known net.
eg, we know lz250 v400 is about same level to elfv2 v800.
and by my testing, sai170 v400 is nearly as strong as lz250 v1.

**Comment by Vandertic** [comment]
Sorry, I thank you for your tests vs LZ250 at v1, but I still find that it is more useful to compare current SAI with old LZ at same visits than current SAI with recent LZ at much lower visits.
Maybe when we are more near to recent LZ we will reconsider though.

**Comment by l1t1** [comment]
i see
