### ISSUE TITLE
The best network was not updated. BUG

### ISSUE THREAD

**Issue by kennyfs** [CuriosAI/sai#96]
Now the promotion and reference are completed, but the self-play is still going on.  I think this is a server error.

**Comment by trinetra75** [comment]
@kennychenfs Thanks for reporting this. We have been changing the pipeline process scripts in the last few days to accomodate the intermittent surges in number of self-plays per hour, but the changes have made the automatisation of the entire process a bit unstable [we have been launching manually and patch a few scripts each time some issue appears].
We should be able to finalise all the scripts within today and the automated process should go back at running as smooth as before...
