### ISSUE TITLE
A question about a recent self-play game

### ISSUE THREAD

**Issue by Splee99** [CuriosAI/sai#97]
Here is a recent self-play game:
http://sai.unich.it/view/897eb90f2cb801704b6aee5231690b44853fea44a04f7f525c48dc052d63b602?viewer=wgo

On the left side there is an obvious capture race situation on move 100, with both group having 6 liberties. However, both b and w choose to ignore it until many moves later. Is this an indication that the 9 block NN structure is not big enough? I don't understand the extra feature of chain size etc. in SAI, but I guess it should be able to count liberties, right?

**Comment by Vandertic** [comment]
The short answer is that I don't know. One could try to analyse the position with SAI and the command eval or with SAI used with sabaki or lizzie.

**Comment by Splee99** [comment]
OK, now I understand the interesting bot vision. SAI does see the capture race but it is not big enough for both.
